version: "3"
services:
  app:
    container_name: react-node-boiler
    restart: always
    build: .
    ports:
      - "3002:3001"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"